version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=mssql
      - DB_PORT=1433
      - DB_USERNAME=sa
      - DB_PASSWORD=YourPassword123
      - DB_DATABASE=SuDoan375
      - JWT_SECRET=your-super-secret-jwt-key
    depends_on:
      - mssql
    volumes:
      - ./uploads:/usr/src/app/uploads

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
